# -*- coding: utf-8 -*-
"""
Added email confirmation to users.

Revision ID: 2d745aa375b8
Revises: f638e40264fe
Create Date: 2020-10-03 19:18:55.535076

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2d745aa375b8"
down_revision = "f638e40264fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email_confirmation_sent_on", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("email_confirmed", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("email_confirmed_on", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("registered_on", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "registered_on")
    op.drop_column("users", "email_confirmed_on")
    op.drop_column("users", "email_confirmed")
    op.drop_column("users", "email_confirmation_sent_on")
    # ### end Alembic commands ###
