# -*- coding: utf-8 -*-
"""
Adding API fields.

Revision ID: 66bd9d73840a
Revises: b91e295482dd
Create Date: 2020-10-10 21:39:25.578788

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "66bd9d73840a"
down_revision = "b91e295482dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stocks",
        sa.Column("curent_price", sa.Integer(), nullable=True),
    )
    op.add_column(
        "stocks",
        sa.Column("current_price_date", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "stocks",
        sa.Column("posistion_value", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stocks", "posistion_value")
    op.drop_column("stocks", "current_price_date")
    op.drop_column("stocks", "curent_price")
    # ### end Alembic commands ###
