# -*- coding: utf-8 -*-
"""
linking user and stock tables.

Revision ID: e1375a0c0990
Revises: 2d745aa375b8
Create Date: 2020-10-08 09:13:29.418056

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e1375a0c0990"
down_revision = "2d745aa375b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stocks", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "stocks", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "stocks", type_="foreignkey")
    op.drop_column("stocks", "user_id")
    # ### end Alembic commands ###
