# -*- coding: utf-8 -*-
"""
add stocks table.

Revision ID: e594c064bec1
Revises:
Create Date: 2020-09-24 11:21:16.124096

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e594c064bec1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stock_symbol", sa.String(), nullable=False),
        sa.Column("number_of_shares", sa.Integer(), nullable=False),
        sa.Column("purchase_price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stocks")
    # ### end Alembic commands ###
