# -*- coding: utf-8 -*-
"""add users table.

Revision ID: f638e40264fe
Revises: e594c064bec1
Create Date: 2020-09-27 10:47:12.479382
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f638e40264fe"
down_revision = "e594c064bec1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hashed", sa.String(length=60), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
